name: TimeCommand
version: '${project.version}'
main: me.evo_es.timecommand.TimeCommand
api-version: '1.13'
authors: [evo_es]
description: TimeCommand
softdepend: [LuckPerms]

commands:
  tmc:
    description: Ejecuta un comando con retardo
    usage: /tmc <comando> <unidad> <cantidad>
    aliases: [TMC]


permissions:
  timecommand.command.tmc:
    default: op
    description: permite usar el comando tmc


